"""Public LiteCut export facade.

Implementation is split by responsibility:
- timeline: project/clip interpretation and timing
- filter_graphs: pure FFmpeg graph construction
- render_pipeline: filesystem, probing and FFmpeg execution

Private helper re-exports are retained for compatibility with existing callers and
focused tests. New code should import from the owning module directly.
"""

from __future__ import annotations

from .ffmpeg_runtime import run_ffmpeg_process as _run_ffmpeg_process
from .filter_graphs import (
    _FILTER_PRESET_VF,
    _ascii_ffmpeg_font_cache_dir,
    _atempo_chain,
    _audio_filter_chain,
    _audio_mix_filter_complex,
    _background_boundary_transition_parts,
    _boundary_transition_filter_complex,
    _build_color_vf,
    _builtin_text_font_file,
    _clip_canvas_transform_graph,
    _clip_video_filter_chain,
    _default_text_font_file,
    _drawtext_alpha_expr,
    _drawtext_filter_complex,
    _drawtext_position_expr,
    _eq_filter,
    _escape_drawtext_value,
    _ffmpeg_expr_time_variable,
    _ffmpeg_filter_path,
    _overlay_filter_complex,
    _overlay_height_from_transform,
    _overlay_keyframe_expr,
    _overlay_layout_from_transform,
    _overlay_opacity_from_transform,
    _pitch_shift_speed_chain,
    _stage_custom_font_for_ffmpeg,
    _text_style_drawtext_options,
    _user_eq_filter,
)
from .render_pipeline import (
    _composite_overlays_on_base,
    _is_looping_animation_file,
    _lite_cut_boundary_transition_to_ts,
    _lite_cut_clip_to_ts,
    _lite_cut_gap_to_ts,
    _mix_audio_tracks_on_base,
    _overlay_video_decoder_args,
    _trim_final_export_range,
    _webm_has_alpha,
    compose_lite_cut_montage,
    export_lite_cut_project,
)
from .timeline import (
    _AUDIO_EXT,
    _MAIN_VIDEO_EXT,
    _TRANSITION_MAP,
    _all_overlay_clips_for_export,
    _audio_track_clips_for_export,
    _base_video_track_for_export,
    _build_positional_transitions,
    _build_transitions,
    _clip_audio_fade,
    _clip_audio_keyframes,
    _clip_canvas_fit,
    _clip_crop_filter,
    _clip_duration_sec,
    _clip_freeze_frame_sec,
    _clip_has_speed_ramp,
    _clip_preserve_pitch,
    _clip_reverse,
    _clip_speed,
    _clip_speed_keyframes,
    _clip_speed_segments,
    _clip_timeline_duration_sec,
    _clip_video_fade,
    _clip_visual_fade,
    _clip_volume,
    _clip_volume_filter,
    _clip_with_track_audio_gain,
    _ffmpeg_color,
    _first_missing_file_asset_for_export,
    _has_soft_positional_transition,
    _has_solo_audio_tracks,
    _is_audio_file_clip,
    _is_file_overlay_clip,
    _is_main_file_clip,
    _is_recorded_timeline_clip,
    _main_video_clips_sorted,
    _map_transition_type,
    _missing_file_assets_for_export,
    _overlay_track_clips,
    _project_bgm_clip_for_export,
    _project_canvas_settings,
    _project_encoder_tier,
    _project_export_range,
    _project_master_volume,
    _project_output_settings,
    _recorded_source_ids_for_export,
    _resolve_audio_clip_paths,
    _resolve_overlay_clip_paths,
    _schema_overlay_clips,
    _timeline_gap_plan,
    _timeline_overlap_pair,
    _timeline_video_layer_clip,
    _track_main_video_clips,
    _track_volume,
    _v1_clips_sorted,
    _v1_main_clips_sorted,
    _v1_recorded_clips_sorted,
    _video_layer_audio_clips_for_export,
)
